#!/usr/bin/env node
/*
 * tasks.js — cross-session task tracker for the Telegram second-brain bot.
 *
 * The bot APPENDS proposals to pending-actions.jsonl (its inbox).
 * Sessions APPEND resolutions to resolutions.jsonl when work is finished.
 * This CLI JOINS the two so every reader sees the TRUE open list instead of
 * the raw (always-stale) inbox. It also regenerates TASKS.md on every run.
 *
 * Usage:
 *   node tasks.js                 # list OPEN tasks (newest first) + refresh TASKS.md
 *   node tasks.js all             # list open + done
 *   node tasks.js show <id>       # full proposal + resolution for one id
 *   node tasks.js done <id> "notes"        # mark completed (appends a resolution)
 *   node tasks.js resolve <id> <status> "notes"   # any status: partial|wontfix|superseded|completed
 *   node tasks.js md              # just (re)write TASKS.md, print nothing else
 *
 * "done" = resolution status matches /complete|done|shipped|resolved/i.
 * Anything else (partial, wontfix, or NO resolution) counts as OPEN.
 */
const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const INBOX = path.join(DIR, 'pending-actions.jsonl');
const RESOL = path.join(DIR, 'resolutions.jsonl');
const MD = path.join(DIR, 'TASKS.md');

const DONE_RE = /complete|done|shipped|resolved/i;              // finished as proposed
const CLOSED_RE = /supersede|wontfix|won'?t fix|skip|drop|declin|obsolete/i; // closed w/o doing
const isClosed = st => DONE_RE.test(st || '') || CLOSED_RE.test(st || '');

function readJsonl(f) {
  if (!fs.existsSync(f)) return [];
  return fs.readFileSync(f, 'utf8').split('\n').filter(Boolean).map(l => {
    try { return JSON.parse(l); } catch { return null; }
  }).filter(Boolean);
}

function load() {
  const pend = {};
  for (const o of readJsonl(INBOX)) if (o.id) pend[o.id] = Object.assign(pend[o.id] || {}, o); // amendments merge
  const res = {};
  for (const o of readJsonl(RESOL)) if (o.id) res[o.id] = o; // last resolution wins
  const rows = Object.values(pend).map(p => {
    const r = res[p.id] || null;
    const done = !!(r && isClosed(r.status));
    return { p, r, done, open: !done };
  });
  rows.sort((a, b) => (b.p.ts || '').localeCompare(a.p.ts || '')); // newest first
  return rows;
}

function line(row) {
  const { p, r } = row;
  const day = (p.ts || '').slice(0, 10);
  const st = r ? r.status : 'no-resolution';
  let s = `• ${p.id}  [${day}]  ${p.action_type || '?'}  <${st}>\n  ${p.summary}`;
  if (r && r.notes) s += `\n  ↳ ${r.notes.slice(0, 200)}`;
  return s;
}

function appendResolution(id, status, notes) {
  const rows = load();
  if (!rows.find(x => x.p.id === id)) {
    console.error(`✗ no proposal with id ${id} in pending-actions.jsonl`);
    process.exit(1);
  }
  const entry = { id, status, ts: new Date().toISOString().replace(/\.\d+Z$/, 'Z'), notes: notes || '' };
  fs.appendFileSync(RESOL, JSON.stringify(entry) + '\n');
  console.log(`✓ recorded ${status} for ${id}`);
  writeMd(load());
}

function writeMd(rows) {
  const open = rows.filter(r => r.open);
  const done = rows.filter(r => r.done);
  const now = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
  let md = `# Second-Brain Bot — Task Tracker\n\n`;
  md += `_Auto-generated by \`tasks.js\` on ${now}. Do not edit by hand — join of \`pending-actions.jsonl\` (inbox) × \`resolutions.jsonl\` (status)._\n\n`;
  md += `**${open.length} open · ${done.length} done · ${rows.length} total**\n\n`;
  md += `## 🟢 Open (${open.length})\n\n`;
  md += open.length ? open.map(r => {
    const { p, r: res } = r;
    let s = `### ${p.summary}\n`;
    s += `- **id:** \`${p.id}\` · **proposed:** ${(p.ts || '').slice(0, 10)} · **type:** ${p.action_type || '?'}\n`;
    if (res) s += `- **status:** ${res.status} — ${res.notes || ''}\n`;
    else s += `- **status:** _no resolution yet_\n`;
    return s;
  }).join('\n') : '_none — inbox fully reconciled._\n';
  md += `\n## ✅ Done / Closed (${done.length})\n\n`;
  md += done.map(r => `- \`${r.p.id}\` [${(r.p.ts || '').slice(0, 10)}] ${r.p.summary} — _${r.r.status}_`).join('\n') + '\n';
  fs.writeFileSync(MD, md);
}

// ---- CLI ----
const [cmd, ...rest] = process.argv.slice(2);
const rows = load();

if (cmd === 'md') {
  writeMd(rows);
  console.log(`✓ wrote ${MD} (${rows.filter(r => r.open).length} open / ${rows.length} total)`);
} else if (cmd === 'done') {
  appendResolution(rest[0], 'completed', rest.slice(1).join(' '));
} else if (cmd === 'resolve') {
  appendResolution(rest[0], rest[1] || 'completed', rest.slice(2).join(' '));
} else if (cmd === 'show') {
  const row = rows.find(r => r.p.id === rest[0]);
  if (!row) { console.error('not found'); process.exit(1); }
  console.log(JSON.stringify(row.p, null, 2));
  console.log('--- resolution ---');
  console.log(row.r ? JSON.stringify(row.r, null, 2) : '(none)');
} else {
  const open = rows.filter(r => r.open);
  const showAll = cmd === 'all';
  console.log(`\n== 🟢 OPEN (${open.length}) ==\n`);
  console.log(open.length ? open.map(line).join('\n\n') : '(none — inbox fully reconciled)');
  if (showAll) {
    const done = rows.filter(r => r.done);
    console.log(`\n\n== ✅ DONE/CLOSED (${done.length}) ==\n`);
    console.log(done.map(r => `• ${r.p.id} [${(r.p.ts || '').slice(0, 10)}] ${r.p.summary}`).join('\n'));
  } else if (rows.length > open.length) {
    console.log(`\n\n(${rows.length - open.length} done — run \`node tasks.js all\` to see them)`);
  }
  writeMd(rows); // keep TASKS.md fresh on every plain read
}
